//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Assignment.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class Comment
    {
        public int CommentID { get; set; }
        public string CommentDescription { get; set; }
        public int PostID { get; set; }
        public int UserID { get; set; }
        [JsonIgnore, XmlIgnore]
        public virtual Post Post { get; set; }
        [JsonIgnore, XmlIgnore]
        public virtual User User { get; set; }
    }
}
